// ROOTRUN — world constants + level definitions (plain JS on purpose: readable/editable).
const STAGE_W = 900, STAGE_H = 400, GROUND_Y = 340;
const LEVELS =
[
          // ── WORLD 1: Tutorial (hacking basics) ──
          {
            name: "W1-1 // BOOT SEQUENCE",
            hint: "Move with arrows, Space to jump. Reach the flagpole. This is the tutorial.",
            hintCost: 10,
            dark: false,
            platforms: [{ x: 0, y: GROUND_Y, w: 900, h: 60 }],
            spikes: [{ x: 400, y: GROUND_Y - 20, w: 22, h: 20 }],
            movingSpikes: [],
            movingPlatforms: [],
            fallingBlocks: [],
            conveyors: [],
            invisiblePlatforms: [],
            spikeBalls: [],
            fireBars: [],
            coins: [
              { x: 150, y: GROUND_Y - 40 },
              { x: 250, y: GROUND_Y - 40 },
              { x: 580, y: GROUND_Y - 40 },
            ],
            tunnel: null,
            gate: null,
            goal: { x: 850 },
          },
          {
            name: "W1-2 // JUMP TUTORIAL",
            hint: "Bigger gap ahead. Time your jump at the edge for maximum distance.",
            hintCost: 10,
            dark: false,
            platforms: [
              { x: 0, y: GROUND_Y, w: 180, h: 60 },
              { x: 370, y: GROUND_Y, w: 100, h: 60 },
              { x: 620, y: GROUND_Y, w: 280, h: 60 },
            ],
            spikes: [{ x: 280, y: GROUND_Y - 20, w: 22, h: 20 }],
            movingSpikes: [],
            movingPlatforms: [],
            fallingBlocks: [],
            conveyors: [],
            invisiblePlatforms: [],
            spikeBalls: [],
            fireBars: [],
            coins: [
              { x: 290, y: GROUND_Y - 50 },
              { x: 490, y: GROUND_Y - 50 },
            ],
            tunnel: null,
            gate: null,
            goal: { x: 850 },
          },
          {
            name: "W1-3 // VARIABLE HACK",
            hint: "The gap is too wide at default speed. But every value you see in the HUD... lives somewhere in the code. Find it.",
            hintCost: 15,
            dark: false,
            platforms: [
              { x: 0, y: GROUND_Y, w: 220, h: 60 },
              { x: 560, y: GROUND_Y, w: 340, h: 60 },
            ],
            spikes: [{ x: 100, y: GROUND_Y - 20, w: 22, h: 20 }],
            movingSpikes: [],
            movingPlatforms: [],
            fallingBlocks: [],
            conveyors: [],
            invisiblePlatforms: [],
            spikeBalls: [],
            fireBars: [],
            coins: [
              { x: 100, y: GROUND_Y - 40 },
              { x: 180, y: GROUND_Y - 40 },
            ],
            tunnel: null,
            gate: null,
            goal: { x: 850 },
          },
          // ── WORLD 2: Intermediate hacking ──
          {
            name: "W2-1 // MEMORY SHRINK",
            hint: "The pipe is too low to walk under. But the 'Size' stat in the HUD isn't just for show... it controls something real.",
            hintCost: 15,
            dark: false,
            platforms: [{ x: 0, y: GROUND_Y, w: 900, h: 60 }],
            spikes: [{ x: 200, y: GROUND_Y - 20, w: 22, h: 20 }, { x: 600, y: GROUND_Y - 20, w: 22, h: 20 }],
            movingSpikes: [],
            movingPlatforms: [],
            fallingBlocks: [],
            conveyors: [],
            invisiblePlatforms: [],
            spikeBalls: [],
            fireBars: [],
            coins: [
              { x: 100, y: GROUND_Y - 40 },
              { x: 300, y: GROUND_Y - 40 },
              { x: 650, y: GROUND_Y - 40 },
            ],
            tunnel: { x: 430, w: 110, openingTop: GROUND_Y - 24 },
            gate: null,
            goal: { x: 850 },
          },
          {
            name: "W2-2 // DOUBLE PIPE",
            hint: "Two pipes, one spike between. The Size stat and Health stat both matter here. Look at the HUD — they're editable.",
            hintCost: 20,
            dark: false,
            platforms: [{ x: 0, y: GROUND_Y, w: 900, h: 60 }],
            spikes: [{ x: 395, y: GROUND_Y - 20, w: 22, h: 20 }],
            movingSpikes: [],
            movingPlatforms: [],
            fallingBlocks: [],
            conveyors: [],
            invisiblePlatforms: [],
            spikeBalls: [],
            fireBars: [],
            coins: [{ x: 500, y: GROUND_Y - 40 }],
            tunnel: { x: 300, w: 80, openingTop: GROUND_Y - 20 },
            tunnel2: { x: 500, w: 80, openingTop: GROUND_Y - 20 },
            gate: null,
            goal: { x: 850 },
          },
          {
            name: "W2-3 // PATROL GRID",
            hint: "Three bots patrol this corridor. They're too fast to dodge. What stats control your movement? The HUD knows.",
            hintCost: 20,
            dark: false,
            platforms: [{ x: 0, y: GROUND_Y, w: 900, h: 60 }],
            spikes: [{ x: 350, y: GROUND_Y - 20, w: 22, h: 20 }, { x: 600, y: GROUND_Y - 20, w: 22, h: 20 }],
            movingSpikes: [
              { baseX: 160, range: 160, speedMul: 1.8, y: GROUND_Y - 20, w: 22, h: 20 },
              { baseX: 410, range: 180, speedMul: 2.2, y: GROUND_Y - 20, w: 22, h: 20 },
              { baseX: 660, range: 140, speedMul: 2.8, y: GROUND_Y - 20, w: 22, h: 20 },
            ],
            movingPlatforms: [],
            fallingBlocks: [],
            conveyors: [
              { x: 250, y: GROUND_Y - 12, w: 150, h: 12, dir: "left", force: 3 },
            ],
            invisiblePlatforms: [],
            spikeBalls: [
              { baseX: 300, range: 250, speed: 2.0, y: GROUND_Y - 24, w: 24, h: 24 },
            ],
            fireBars: [],
            coins: [{ x: 120, y: GROUND_Y - 40 }, { x: 550, y: GROUND_Y - 40 }, { x: 800, y: GROUND_Y - 40 }],
            tunnel: null,
            gate: null,
            goal: { x: 850 },
          },
          // ── WORLD 3: Gate hacking ──
          {
            name: "W3-1 // CREDIT LOCK",
            hint: "The gate demands 500 credits. There aren't enough coins in this level. But where does the 'Coins' number come from?...",
            hintCost: 20,
            dark: false,
            platforms: [{ x: 0, y: GROUND_Y, w: 900, h: 60 }],
            spikes: [{ x: 350, y: GROUND_Y - 20, w: 22, h: 20 }],
            movingSpikes: [
              { baseX: 500, range: 120, speedMul: 2.0, y: GROUND_Y - 20, w: 22, h: 20 },
            ],
            movingPlatforms: [],
            fallingBlocks: [],
            conveyors: [
              { x: 500, y: GROUND_Y - 12, w: 130, h: 12, dir: "left", force: 3 },
            ],
            invisiblePlatforms: [],
            spikeBalls: [
              { baseX: 200, range: 300, speed: 1.8, y: GROUND_Y - 24, w: 24, h: 24 },
            ],
            fireBars: [],
            coins: [
              { x: 100, y: GROUND_Y - 40 },
              { x: 170, y: GROUND_Y - 40 },
              { x: 240, y: GROUND_Y - 40 },
              { x: 310, y: GROUND_Y - 40 },
              { x: 380, y: GROUND_Y - 40 },
              { x: 450, y: GROUND_Y - 40 },
            ],
            tunnel: null,
            gate: { x: 700, w: 14, required: 500 },
            goal: { x: 850 },
          },
          {
            name: "W3-2 // ELEMENT EDIT",
            hint: "The gate shows 'requires 999' in the DOM. Every element on screen has properties you can read... and write.",
            hintCost: 20,
            dark: false,
            platforms: [{ x: 0, y: GROUND_Y, w: 900, h: 60 }],
            spikes: [],
            movingSpikes: [
              { baseX: 380, range: 170, speedMul: 2.2, y: GROUND_Y - 20, w: 22, h: 20 },
            ],
            movingPlatforms: [],
            fallingBlocks: [],
            conveyors: [],
            invisiblePlatforms: [],
            spikeBalls: [],
            fireBars: [],
            coins: [{ x: 150, y: GROUND_Y - 40 }, { x: 250, y: GROUND_Y - 40 }],
            tunnel: null,
            gate: { x: 600, w: 14, required: 999 },
            goal: { x: 850 },
          },
          {
            name: "W3-3 // MOVE LOCK",
            hint: "Speed resets to 0.5 every time you start. The lock runs in the code, but the variable itself is still out in the open...",
            hintCost: 25,
            dark: false,
            platforms: [
              { x: 0, y: GROUND_Y, w: 160, h: 60 },
              { x: 310, y: GROUND_Y, w: 100, h: 60 },
              { x: 500, y: GROUND_Y, w: 100, h: 60 },
              { x: 720, y: GROUND_Y, w: 180, h: 60 },
            ],
            spikes: [{ x: 250, y: GROUND_Y - 20, w: 22, h: 20 }, { x: 620, y: GROUND_Y - 20, w: 22, h: 20 }],
            movingSpikes: [],
            movingPlatforms: [],
            fallingBlocks: [],
            conveyors: [],
            invisiblePlatforms: [],
            spikeBalls: [],
            fireBars: [],
            coins: [{ x: 400, y: GROUND_Y - 50 }],
            tunnel: null,
            gate: null,
            goal: { x: 850 },
            speedLock: 0.5,
          },
          // ── WORLD 4: Moving platforms & timing ──
          {
            name: "W4-1 // PLATFORM JUMP",
            hint: "Blue platforms move horizontally. Time your jumps to land on them and ride across the gaps.",
            hintCost: 25,
            dark: false,
            platforms: [
              { x: 0, y: GROUND_Y, w: 140, h: 60 },
              { x: 760, y: GROUND_Y, w: 140, h: 60 },
            ],
            spikes: [{ x: 350, y: GROUND_Y - 20, w: 22, h: 20 }],
            movingSpikes: [],
            movingPlatforms: [
              { x: 180, y: GROUND_Y - 40, w: 90, h: 16, moveX: 180, speed: 1.8 },
              { x: 480, y: GROUND_Y - 80, w: 90, h: 16, moveX: 150, speed: 2.4 },
            ],
            fallingBlocks: [],
            conveyors: [],
            invisiblePlatforms: [],
            spikeBalls: [],
            fireBars: [],
            coins: [
              { x: 260, y: GROUND_Y - 80 },
              { x: 560, y: GROUND_Y - 120 },
            ],
            tunnel: null,
            gate: null,
            goal: { x: 850 },
          },
          {
            name: "W4-2 // CRUMBLE BRIDGE",
            hint: "Brown blocks crumble when you step on them. Move fast or increase jumpPower to clear them in fewer touches.",
            hintCost: 25,
            dark: false,
            platforms: [
              { x: 0, y: GROUND_Y, w: 130, h: 60 },
              { x: 770, y: GROUND_Y, w: 130, h: 60 },
            ],
            spikes: [{ x: 340, y: GROUND_Y - 20, w: 22, h: 20 }],
            movingSpikes: [],
            movingPlatforms: [],
            fallingBlocks: [
              { x: 180, y: GROUND_Y, w: 55, h: 20, delay: 700 },
              { x: 250, y: GROUND_Y, w: 55, h: 20, delay: 700 },
              { x: 320, y: GROUND_Y, w: 55, h: 20, delay: 700 },
              { x: 395, y: GROUND_Y, w: 55, h: 20, delay: 700 },
              { x: 470, y: GROUND_Y, w: 55, h: 20, delay: 700 },
              { x: 545, y: GROUND_Y, w: 55, h: 20, delay: 700 },
              { x: 620, y: GROUND_Y, w: 55, h: 20, delay: 700 },
            ],
            conveyors: [],
            invisiblePlatforms: [],
            spikeBalls: [],
            fireBars: [],
            coins: [{ x: 370, y: GROUND_Y - 40 }, { x: 600, y: GROUND_Y - 40 }],
            tunnel: null,
            gate: null,
            goal: { x: 850 },
          },
          {
            name: "W4-3 // CONVEYOR DASH",
            hint: "Conveyor belts push you left or right. Green arrows show direction. Use speed to fight the current or ride it.",
            hintCost: 25,
            dark: false,
            platforms: [
              { x: 0, y: GROUND_Y, w: 900, h: 60 },
            ],
            spikes: [{ x: 500, y: GROUND_Y - 20, w: 22, h: 20 }],
            movingSpikes: [
              { baseX: 300, range: 100, speedMul: 1.5, y: GROUND_Y - 20, w: 22, h: 20 },
            ],
            movingPlatforms: [],
            fallingBlocks: [],
            conveyors: [
              { x: 180, y: GROUND_Y - 12, w: 220, h: 12, dir: "right", force: 3.5 },
              { x: 530, y: GROUND_Y - 12, w: 260, h: 12, dir: "left", force: 4.5 },
            ],
            invisiblePlatforms: [],
            spikeBalls: [],
            fireBars: [],
            coins: [
              { x: 280, y: GROUND_Y - 40 },
              { x: 650, y: GROUND_Y - 40 },
            ],
            tunnel: null,
            gate: null,
            goal: { x: 850 },
          },
          // ── WORLD 5: Advanced obstacles ──
          {
            name: "W5-1 // INVISIBLE PATH",
            hint: "Platforms are hidden! Walk near them to reveal. But the Elements tab shows everything — even things you can't see.",
            hintCost: 30,
            dark: false,
            platforms: [
              { x: 0, y: GROUND_Y, w: 130, h: 60 },
              { x: 770, y: GROUND_Y, w: 130, h: 60 },
            ],
            spikes: [{ x: 350, y: GROUND_Y - 20, w: 22, h: 20 }],
            movingSpikes: [],
            movingPlatforms: [],
            fallingBlocks: [],
            conveyors: [],
            invisiblePlatforms: [
              { x: 200, y: GROUND_Y - 30, w: 90, h: 12 },
              { x: 380, y: GROUND_Y - 70, w: 90, h: 12 },
              { x: 560, y: GROUND_Y - 40, w: 90, h: 12 },
              { x: 700, y: GROUND_Y - 60, w: 90, h: 12 },
            ],
            spikeBalls: [],
            fireBars: [],
            coins: [
              { x: 240, y: GROUND_Y - 70 },
              { x: 420, y: GROUND_Y - 110 },
              { x: 600, y: GROUND_Y - 80 },
              { x: 740, y: GROUND_Y - 100 },
            ],
            tunnel: null,
            gate: null,
            goal: { x: 850 },
          },
          {
            name: "W5-2 // SPIKE GAUNTLET",
            hint: "Spike balls everywhere. Dodging them all is nearly impossible at default stats. The HUD's Health number might need a boost.",
            hintCost: 30,
            dark: false,
            platforms: [{ x: 0, y: GROUND_Y, w: 900, h: 60 }],
            spikes: [{ x: 250, y: GROUND_Y - 20, w: 22, h: 20 }, { x: 650, y: GROUND_Y - 20, w: 22, h: 20 }],
            movingSpikes: [],
            movingPlatforms: [],
            fallingBlocks: [],
            conveyors: [],
            invisiblePlatforms: [],
            spikeBalls: [
              { baseX: 80, range: 720, speed: 2.2, y: GROUND_Y - 24, w: 24, h: 24 },
              { baseX: 820, range: 650, speed: 1.8, y: GROUND_Y - 24, w: 24, h: 24, phase: 3.14 },
              { baseX: 400, range: 400, speed: 2.5, y: GROUND_Y - 24, w: 24, h: 24, phase: 1.5 },
            ],
            fireBars: [],
            coins: [
              { x: 300, y: GROUND_Y - 50 },
              { x: 500, y: GROUND_Y - 50 },
            ],
            tunnel: null,
            gate: null,
            goal: { x: 850 },
          },
          {
            name: "W5-3 // FIRE ROW",
            hint: "Rotating fire bars block the path. Each one has a pivot point and an arm length — they're real DOM elements with real positions.",
            hintCost: 30,
            dark: false,
            platforms: [{ x: 0, y: GROUND_Y, w: 900, h: 60 }],
            spikes: [{ x: 150, y: GROUND_Y - 20, w: 22, h: 20 }],
            movingSpikes: [],
            movingPlatforms: [],
            fallingBlocks: [],
            conveyors: [],
            invisiblePlatforms: [],
            spikeBalls: [],
            fireBars: [
              { x: 230, y: GROUND_Y - 40, armLen: 75, speed: 1.8 },
              { x: 460, y: GROUND_Y - 40, armLen: 85, speed: -2.2 },
              { x: 680, y: GROUND_Y - 40, armLen: 70, speed: 2.0 },
            ],
            coins: [
              { x: 130, y: GROUND_Y - 40 },
              { x: 350, y: GROUND_Y - 40 },
              { x: 580, y: GROUND_Y - 40 },
            ],
            tunnel: null,
            gate: null,
            goal: { x: 850 },
          },
          // ── WORLD 6: Combo challenges ──
          {
            name: "W6-1 // MIXED SIGNALS",
            hint: "Moving platforms over spike pits. One wrong jump and it's over. You might need a jumpPower boost.",
            hintCost: 30,
            dark: false,
            platforms: [
              { x: 0, y: GROUND_Y, w: 110, h: 60 },
              { x: 790, y: GROUND_Y, w: 110, h: 60 },
            ],
            spikes: [
              { x: 180, y: GROUND_Y - 20, w: 22, h: 20 },
              { x: 630, y: GROUND_Y - 20, w: 22, h: 20 },
            ],
            movingSpikes: [
              { baseX: 360, range: 90, speedMul: 2.8, y: GROUND_Y - 20, w: 22, h: 20 },
            ],
            movingPlatforms: [
              { x: 160, y: GROUND_Y - 50, w: 85, h: 16, moveX: 140, speed: 2.0 },
              { x: 430, y: GROUND_Y - 90, w: 85, h: 16, moveX: 160, speed: 2.5 },
              { x: 620, y: GROUND_Y - 40, w: 85, h: 16, moveX: 120, speed: 1.8 },
            ],
            fallingBlocks: [],
            conveyors: [],
            invisiblePlatforms: [],
            spikeBalls: [],
            fireBars: [],
            coins: [
              { x: 220, y: GROUND_Y - 90 },
              { x: 500, y: GROUND_Y - 130 },
            ],
            tunnel: null,
            gate: null,
            goal: { x: 850 },
          },
          {
            name: "W6-2 // INVISIBLE GAUNTLET",
            hint: "Hidden platforms over spikes. One wrong step means death. The DOM holds the layout of every invisible block...",
            hintCost: 30,
            dark: false,
            platforms: [
              { x: 0, y: GROUND_Y, w: 100, h: 60 },
              { x: 800, y: GROUND_Y, w: 100, h: 60 },
            ],
            spikes: [
              { x: 180, y: GROUND_Y - 20, w: 30, h: 20 },
              { x: 330, y: GROUND_Y - 20, w: 30, h: 20 },
              { x: 480, y: GROUND_Y - 20, w: 30, h: 20 },
              { x: 630, y: GROUND_Y - 20, w: 30, h: 20 },
            ],
            movingSpikes: [],
            movingPlatforms: [],
            fallingBlocks: [],
            conveyors: [],
            invisiblePlatforms: [
              { x: 160, y: GROUND_Y - 40, w: 75, h: 12 },
              { x: 300, y: GROUND_Y - 80, w: 75, h: 12 },
              { x: 440, y: GROUND_Y - 50, w: 75, h: 12 },
              { x: 580, y: GROUND_Y - 90, w: 75, h: 12 },
              { x: 700, y: GROUND_Y - 40, w: 75, h: 12 },
            ],
            spikeBalls: [],
            fireBars: [],
            coins: [
              { x: 190, y: GROUND_Y - 80 },
              { x: 470, y: GROUND_Y - 90 },
              { x: 730, y: GROUND_Y - 80 },
            ],
            tunnel: null,
            gate: null,
            goal: { x: 850 },
          },
          {
            name: "W6-3 // FULL GAUNTLET",
            hint: "Everything combined. Moving platforms, crumble blocks, fire bars, and spike balls. Or hack everything at once.",
            hintCost: 35,
            dark: false,
            platforms: [
              { x: 0, y: GROUND_Y, w: 90, h: 60 },
              { x: 810, y: GROUND_Y, w: 90, h: 60 },
            ],
            spikes: [{ x: 400, y: GROUND_Y - 20, w: 22, h: 20 }],
            movingSpikes: [
              { baseX: 550, range: 120, speedMul: 2.0, y: GROUND_Y - 20, w: 22, h: 20 },
            ],
            movingPlatforms: [
              { x: 120, y: GROUND_Y - 60, w: 75, h: 16, moveX: 100, speed: 2.2 },
            ],
            fallingBlocks: [
              { x: 280, y: GROUND_Y, w: 48, h: 20, delay: 550 },
              { x: 340, y: GROUND_Y, w: 48, h: 20, delay: 550 },
            ],
            conveyors: [
              { x: 440, y: GROUND_Y - 12, w: 130, h: 12, dir: "right", force: 3.5 },
            ],
            invisiblePlatforms: [
              { x: 600, y: GROUND_Y - 50, w: 75, h: 12 },
            ],
            spikeBalls: [
              { baseX: 280, range: 320, speed: 2.0, y: GROUND_Y - 24, w: 24, h: 24 },
            ],
            fireBars: [
              { x: 730, y: GROUND_Y - 40, armLen: 65, speed: 2.2 },
            ],
            coins: [
              { x: 160, y: GROUND_Y - 100 },
              { x: 480, y: GROUND_Y - 50 },
              { x: 680, y: GROUND_Y - 90 },
            ],
            tunnel: null,
            gate: null,
            goal: { x: 850 },
          },
          // ── WORLD 7: The Final Challenge ──
          {
            name: "W7-1 // NIGHT SHIFT",
            hint: "Dark skies. Everything moves faster here. You'll need speed=15+ and jumpPower=20+ to survive.",
            hintCost: 35,
            dark: true,
            platforms: [
              { x: 0, y: GROUND_Y, w: 110, h: 60 },
              { x: 790, y: GROUND_Y, w: 110, h: 60 },
            ],
            spikes: [],
            movingSpikes: [
              { baseX: 280, range: 220, speedMul: 3.2, y: GROUND_Y - 20, w: 22, h: 20 },
              { baseX: 580, range: 170, speedMul: 3.8, y: GROUND_Y - 20, w: 22, h: 20 },
            ],
            movingPlatforms: [
              { x: 140, y: GROUND_Y - 70, w: 75, h: 16, moveX: 120, speed: 2.8 },
              { x: 380, y: GROUND_Y - 110, w: 75, h: 16, moveX: 140, speed: 3.2 },
              { x: 630, y: GROUND_Y - 60, w: 75, h: 16, moveX: 100, speed: 3.0 },
            ],
            fallingBlocks: [
              { x: 330, y: GROUND_Y, w: 48, h: 20, delay: 350 },
            ],
            conveyors: [
              { x: 510, y: GROUND_Y - 12, w: 110, h: 12, dir: "left", force: 5.5 },
            ],
            invisiblePlatforms: [
              { x: 710, y: GROUND_Y - 80, w: 65, h: 12 },
            ],
            spikeBalls: [
              { baseX: 180, range: 520, speed: 2.8, y: GROUND_Y - 24, w: 24, h: 24 },
              { baseX: 600, range: 300, speed: 3.2, y: GROUND_Y - 24, w: 24, h: 24, phase: 2 },
            ],
            fireBars: [
              { x: 430, y: GROUND_Y - 50, armLen: 75, speed: 2.8 },
            ],
            coins: [
              { x: 200, y: GROUND_Y - 110 },
              { x: 450, y: GROUND_Y - 150 },
              { x: 680, y: GROUND_Y - 100 },
            ],
            tunnel: null,
            gate: null,
            goal: { x: 850 },
          },
          {
            name: "W7-2 // CREDIT WALL",
            hint: "Three gates, massive coin requirements. You won't collect enough. The gate values live in the DOM — every attribute is editable.",
            hintCost: 35,
            dark: true,
            platforms: [{ x: 0, y: GROUND_Y, w: 900, h: 60 }],
            spikes: [{ x: 200, y: GROUND_Y - 20, w: 22, h: 20 }],
            movingSpikes: [
              { baseX: 480, range: 140, speedMul: 2.8, y: GROUND_Y - 20, w: 22, h: 20 },
            ],
            movingPlatforms: [],
            fallingBlocks: [],
            conveyors: [],
            invisiblePlatforms: [],
            spikeBalls: [],
            fireBars: [],
            coins: [{ x: 100, y: GROUND_Y - 40 }, { x: 300, y: GROUND_Y - 40 }],
            tunnel: null,
            gate: { x: 400, w: 14, required: 3000 },
            gate2: { x: 600, w: 14, required: 5000 },
            gate3: { x: 780, w: 14, required: 8000 },
            goal: { x: 850 },
          },
          {
            name: "W7-3 // ROOT ACCESS FINAL",
            hint: "The ultimate test. Stats are locked on load, the DOM fights back, and every obstacle is tuned to kill. Time to use everything you've learned.",
            hintCost: 40,
            dark: true,
            platforms: [
              { x: 0, y: GROUND_Y, w: 70, h: 60 },
              { x: 830, y: GROUND_Y, w: 70, h: 60 },
            ],
            spikes: [],
            movingSpikes: [
              { baseX: 230, range: 220, speedMul: 3.2, y: GROUND_Y - 20, w: 22, h: 20 },
              { baseX: 580, range: 200, speedMul: 3.8, y: GROUND_Y - 20, w: 22, h: 20 },
            ],
            movingPlatforms: [
              { x: 110, y: GROUND_Y - 60, w: 65, h: 16, moveX: 100, speed: 3.2 },
              { x: 330, y: GROUND_Y - 100, w: 65, h: 16, moveX: 120, speed: 3.8 },
              { x: 560, y: GROUND_Y - 70, w: 65, h: 16, moveX: 100, speed: 3.0 },
              { x: 720, y: GROUND_Y - 50, w: 65, h: 16, moveX: 60, speed: 2.2 },
            ],
            fallingBlocks: [
              { x: 260, y: GROUND_Y, w: 48, h: 20, delay: 450 },
              { x: 430, y: GROUND_Y, w: 48, h: 20, delay: 450 },
            ],
            conveyors: [
              { x: 480, y: GROUND_Y - 12, w: 110, h: 12, dir: "right", force: 5.5 },
            ],
            invisiblePlatforms: [
              { x: 190, y: GROUND_Y - 120, w: 55, h: 12 },
              { x: 660, y: GROUND_Y - 90, w: 55, h: 12 },
            ],
            spikeBalls: [
              { baseX: 130, range: 620, speed: 3.0, y: GROUND_Y - 24, w: 24, h: 24 },
              { baseX: 680, range: 420, speed: 3.5, y: GROUND_Y - 24, w: 24, h: 24, phase: 2 },
            ],
            fireBars: [
              { x: 280, y: GROUND_Y - 50, armLen: 72, speed: 3.2 },
              { x: 630, y: GROUND_Y - 50, armLen: 62, speed: -2.8 },
            ],
            coins: [
              { x: 150, y: GROUND_Y - 100 },
              { x: 380, y: GROUND_Y - 140 },
              { x: 600, y: GROUND_Y - 110 },
            ],
            tunnel: null,
            gate: null,
            goal: { x: 850 },
            healthLock: 30,
            speedLock: 1.0,
          },
        ];
